name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this trigger for manual workflow dispatches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Build Script
        run: echo "Hello, World!"
